package com.neueda.tms.service.rule;

import com.neueda.tms.service.alert.AuditTrailService;
import com.neueda.tms.repository.transaction.Transaction;
import com.neueda.tms.repository.alert.Alert;
import com.neueda.tms.repository.alert.AlertAuditTrail;
import com.neueda.tms.repository.rule.MonitoringRule;
import com.neueda.tms.repository.alert.AlertRepository;
import com.neueda.tms.repository.rule.MonitoringRuleRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Core monitoring engine.
 * Evaluates a transaction synchronously against all active rules and generates alerts.
 */
@Service
public class MonitoringEngineService {
    private static final Logger log = LoggerFactory.getLogger(MonitoringEngineService.class);


    private final MonitoringRuleRepository ruleRepository;
    private final AlertRepository alertRepository;
    private final AuditTrailService auditTrailService;
    private final List<RuleEvaluator> evaluators;

    @Autowired
    public MonitoringEngineService(MonitoringRuleRepository ruleRepository,
                                   AlertRepository alertRepository,
                                   AuditTrailService auditTrailService,
                                   List<RuleEvaluator> evaluators) {
        this.ruleRepository = ruleRepository;
        this.alertRepository = alertRepository;
        this.auditTrailService = auditTrailService;
        this.evaluators = evaluators;
    }

    @Transactional
    public List<Alert> evaluate(Transaction transaction) {
        // Build evaluator map keyed by rule code for O(1) lookup
        Map<String, RuleEvaluator> evaluatorMap = evaluators.stream()
                .collect(Collectors.toMap(RuleEvaluator::getRuleCode, Function.identity()));

        List<MonitoringRule> activeRules = ruleRepository.findByIsActiveTrue();
        List<Alert> generatedAlerts = new ArrayList<>();

        for (MonitoringRule rule : activeRules) {
            RuleEvaluator evaluator = evaluatorMap.get(rule.getRuleCode());
            if (evaluator == null) {
                log.warn("No evaluator found for rule code: {}", rule.getRuleCode());
                continue;
            }

            try {
                Optional<String> triggerDescription = evaluator.evaluate(transaction, rule);
                if (triggerDescription.isPresent()) {
                    Alert alert = new Alert(
                            null, // id
                            transaction,
                            rule,
                            Alert.AlertStatus.OPEN,
                            evaluator.getSeverity(rule),
                            triggerDescription.get(),
                            null, // assignedTo
                            LocalDateTime.now(),
                            null  // updatedAt
                    );

                    Alert savedAlert = alertRepository.save(alert);
                    generatedAlerts.add(savedAlert);

                    // Record audit trail entry
                    auditTrailService.recordAction(
                            savedAlert,
                            AlertAuditTrail.AuditAction.CREATED,
                            "SYSTEM",
                            "Alert auto-generated by rule: " + rule.getRuleName()
                    );

                    log.info("Alert generated - Rule: {}, Transaction: {}, Severity: {}",
                            rule.getRuleCode(), transaction.getTransactionRef(), savedAlert.getSeverity());
                }
            } catch (Exception e) {
                log.error("Error evaluating rule {} for transaction {}: {}",
                        rule.getRuleCode(), transaction.getTransactionRef(), e.getMessage());
            }
        }

        log.info("Monitoring complete for transaction {} — {} alert(s) generated",
                transaction.getTransactionRef(), generatedAlerts.size());
        return generatedAlerts;
    }
}
