package com.neueda.tms.service.rule;

import com.neueda.tms.repository.alert.Alert;
import com.neueda.tms.repository.rule.MonitoringRule;
import com.neueda.tms.repository.transaction.Transaction;

import java.util.Optional;

/**
 * Interface for all monitoring rule evaluators.
 * Each evaluator is responsible for one specific rule code.
 */
public interface RuleEvaluator {

    /**
     * @return the rule code this evaluator handles (must match monitoring_rules.rule_code)
     */
    String getRuleCode();

    /**
     * Evaluate the transaction against this rule.
     *
     * @param transaction the transaction to evaluate
     * @param rule        the rule entity with current parameters
     * @return Optional containing alert description if triggered, empty if not triggered
     */
    Optional<String> evaluate(Transaction transaction, MonitoringRule rule);

    /**
     * @return the severity of alerts generated by this rule
     */
    Alert.AlertSeverity getSeverity(MonitoringRule rule);
}
